Unit_Root_mex.mexw64
Unit_Root		Unit_Root
Unit_Root_atexit		Unit_Root_atexit
Unit_Root_initialize		Unit_Root_initialize
Unit_Root_terminate		Unit_Root_terminate
d_error		d_error
disp		disp
emlrtMexFcnProperties		emlrtMexFcnProperties
emxEnsureCapacity_real_T		emxEnsureCapacity_real_T
emxFree_real_T		emxFree_real_T
emxInit_real_T		emxInit_real_T
mexFunction		mexFunction
mexfilerequiredapiversion		mexfilerequiredapiversion
