set COMPILER=lcc 
				set COMPFLAGS=-c -noregistrylookup -DMX_COMPAT_32  -DMATLAB_MEX_FILE -I"D:\MATLAB\R2015b\sys\lcc\include" -I"D:\MATLAB\R2015b\extern\include" -I"D:\MATLAB\R2015b\simulink\include" -I"D:\MATLAB\R2015b\sys\lcc\mex"   
				set OPTIMFLAGS= -DNDEBUG 
				set DEBUGFLAGS=-g4 
				set LINKER="D:\MATLAB\R2015b\sys\lcc\bin\lcclnk" 
				set LINKFLAGS= -dll "%MATLAB%\extern\lib\win32\lcc\%ENTRYPOINT%.def" -L"D:\MATLAB\R2015b\sys\lcc\lib" -libpath "D:\MATLAB\R2015b\extern\lib\win32\lcc" -libpath "D:\MATLAB\R2015b\lib\win32" "%LIB_NAME%2.obj"
				set LINKFLAGSPOST=libmx.lib libmex.lib libmat.lib 
				set LINKDEBUGFLAGS=
				set NAME_OUTPUT=/out:"%OUTDIR%%MEX_NAME%%MEX_EXT%"
set PATH=D:\MATLAB\R2015b\sys\lcc\bin;D:\MATLAB\R2015b\sys\lcc\include;D:\MATLAB\R2015b\sys\lcc\mex;D:\MATLAB\R2015b\extern\lib\win32\lcc;D:\MATLAB\R2015b\extern\include\win32\;D:\MATLAB\R2015b\extern\include;D:\MATLAB\R2015b\simulink\include;D:\MATLAB\R2015b\lib\win32;%MATLAB_BIN%;%PATH%
set INCLUDE=D:\MATLAB\R2015b\extern\include;;%INCLUDE%
set LIB=D:\MATLAB\R2015b\lib\win32;D:\MATLAB\R2015b\extern\lib\win32\lcc;;%LIB%
set LIBPATH=D:\MATLAB\R2015b\extern\lib\win32\lcc;D:\MATLAB\R2015b\sys\lcc\lib\;D:\MATLAB\R2015b\sys\lcc\mex;%LIBPATH%
